kind: ConfigMap
apiVersion: v1
data:
  system.input.conf: |-
    <source>
      type tail
      path /var/lib/docker/containers/*/*-json.log
      pos_file fluentd-docker.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag docker.*
      format json
      read_from_head true
    </source>
    <match docker.var.lib.docker.containers.*.*.log>
      type kubernetes
      container_id ${tag_parts[5]}
      tag docker.${name}
    </match>
    <filter kubernetes>
      type grep
      <regexp>
        key hackgtmetricsversion
        pattern 1
      </regexp>
    </filter>
    <match kubernetes>
      type influxdb
      host  influxdb-influxdb.monitoring.svc.cluster.local
      port  8086
      dbname metrics
      use_ssl false
      retry 5
      retry_limit 5
    </match>
    <match kubernetes>
      type stdout
    </match>
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
